### ISSUE TITLE
Update dependencies  

### ISSUE THREAD

**Issue by rsvoboda** [jirban/jirban-jira#140]
$ yarn outdated
```
Package                           Current Wanted Latest Package Type    URL                                                                               
@angular/common                   2.4.5   2.4.5  4.0.1  dependencies    https://github.com/angular/angular#readme                                         
angular2-template-loader          0.6.0   0.6.0  0.6.2  devDependencies https://github.com/TheLarkInn/angular2-template-loader#readme                     
css-loader                        0.26.1  0.26.1 0.28.0 devDependencies https://github.com/webpack/css-loader#readme                                      
extract-text-webpack-plugin       1.0.1   1.0.1  2.1.0  devDependencies http://github.com/webpack/extract-text-webpack-plugin                             
file-loader                       0.10.0  0.10.0 0.11.0 devDependencies https://github.com/webpack/file-loader                                            
zone.js                           0.7.6   0.7.6  0.8.5  dependencies    https://github.com/angular/zone.js#readme                                         
karma                             1.3.0   1.3.0  1.5.0  devDependencies http://karma-runner.github.io/                                                    
karma-jasmine                     1.0.2   1.0.2  1.1.0  devDependencies https://github.com/karma-runner/karma-jasmine#readme                              
karma-mocha-reporter              2.1.0   2.1.0  2.2.3  devDependencies http://www.litixsoft.de/index.php?lang=en#modules                                 
karma-phantomjs-launcher          1.0.2   1.0.2  1.0.4  devDependencies https://github.com/karma-runner/karma-phantomjs-launcher#readme                   
karma-webpack                     1.8.1   1.8.1  2.0.3  devDependencies http://github.com/webpack/karma-webpack                                           
rxjs                              5.1.0   5.1.0  5.2.0  dependencies    https://github.com/ReactiveX/RxJS                                                 
rimraf                            2.5.4   2.5.4  2.6.1  devDependencies https://github.com/isaacs/rimraf#readme                                           
reflect-metadata                  0.1.9   0.1.9  0.1.10 dependencies    http://rbuckton.github.io/reflect-metadata                                        
style-loader                      0.13.1  0.13.1 0.16.1 devDependencies https://github.com/webpack/style-loader#readme                                    
@angular/upgrade                  2.4.5   2.4.5  4.0.1  dependencies    https://github.com/angular/angular#readme                                         
ts-loader                         0.8.2   0.8.2  2.0.3  devDependencies https://github.com/TypeStrong/ts-loader                                           
@angular/router                   3.4.5   3.4.5  4.0.1  dependencies    https://github.com/angular/angular/blob/master/modules/%40angular/router/README.md
typescript                        2.0.3   2.0.3  2.2.2  devDependencies http://typescriptlang.org/                                                        
@angular/platform-browser-dynamic 2.4.5   2.4.5  4.0.1  dependencies    https://github.com/angular/angular#readme                                         
webpack                           1.14.0  1.14.0 2.3.2  devDependencies https://github.com/webpack/webpack                                                
@angular/platform-browser         2.4.5   2.4.5  4.0.1  dependencies    https://github.com/angular/angular#readme                                         
webpack-dev-server                1.16.3  1.16.3 2.4.2  devDependencies http://github.com/webpack/webpack-dev-server                                      
@angular/http                     2.4.5   2.4.5  4.0.1  dependencies    https://github.com/angular/angular#readme                                         
webpack-merge                     0.20.0  0.20.0 4.1.0  devDependencies https://github.com/survivejs/webpack-merge                                        
@angular/forms                    2.4.5   2.4.5  4.0.1  dependencies    https://github.com/angular/angular#readme                                         
@types/core-js                    0.9.35  0.9.35 0.9.41 devDependencies https://www.github.com/DefinitelyTyped/DefinitelyTyped.git                        
@angular/core                     2.4.5   2.4.5  4.0.1  dependencies    https://github.com/angular/angular#readme                                         
@types/node                       7.0.4   7.0.4  7.0.12 devDependencies https://www.github.com/DefinitelyTyped/DefinitelyTyped.git                        
@angular/compiler                 2.4.5   2.4.5  4.0.1  dependencies    https://github.com/angular/angular#readme                                         
@types/jasmine                    2.5.41  2.5.41 2.5.47 devDependencies https://www.github.com/DefinitelyTyped/DefinitelyTyped.git                        
html-loader                       0.4.4   0.4.4  0.4.5  devDependencies https://github.com/webpack/html-loader#readme 
```

**Comment by kabir** [comment]
The latest of each isn't always compatible with others, especially when there is a minor/major upgrade. It is a puzzle :)

**Comment by rsvoboda** [comment]
I know, upgrade to Angular 4 is probably not the best thing now :) Trying to filter out only micro upgrades

**Comment by rsvoboda** [comment]
Micro updates:
```
angular2-template-loader          0.6.0   0.6.0  0.6.2  devDependencies https://github.com/TheLarkInn/angular2-template-loader#readme                     
karma-phantomjs-launcher          1.0.2   1.0.2  1.0.4  devDependencies https://github.com/karma-runner/karma-phantomjs-launcher#readme                   
reflect-metadata                  0.1.9   0.1.9  0.1.10 dependencies    http://rbuckton.github.io/reflect-metadata                                        
@types/core-js                    0.9.35  0.9.35 0.9.41 devDependencies https://www.github.com/DefinitelyTyped/DefinitelyTyped.git                        
@types/node                       7.0.4   7.0.4  7.0.12 devDependencies https://www.github.com/DefinitelyTyped/DefinitelyTyped.git                        
@types/jasmine                    2.5.41  2.5.41 2.5.47 devDependencies https://www.github.com/DefinitelyTyped/DefinitelyTyped.git                        
html-loader                       0.4.4   0.4.4  0.4.5  devDependencies https://github.com/webpack/html-loader#readme 
```

**Comment by rsvoboda** [comment]
Minor updates:
```
css-loader                        0.26.1  0.26.1 0.28.0 devDependencies https://github.com/webpack/css-loader#readme                                      
file-loader                       0.10.0  0.10.0 0.11.0 devDependencies https://github.com/webpack/file-loader                                            
zone.js                           0.7.6   0.7.6  0.8.5  dependencies    https://github.com/angular/zone.js#readme                                         
karma                             1.3.0   1.3.0  1.5.0  devDependencies http://karma-runner.github.io/                                                    
karma-jasmine                     1.0.2   1.0.2  1.1.0  devDependencies https://github.com/karma-runner/karma-jasmine#readme                              
karma-mocha-reporter              2.1.0   2.1.0  2.2.3  devDependencies http://www.litixsoft.de/index.php?lang=en#modules                                 
rxjs                              5.1.0   5.1.0  5.2.0  dependencies    https://github.com/ReactiveX/RxJS                                                 
rimraf                            2.5.4   2.5.4  2.6.1  devDependencies https://github.com/isaacs/rimraf#readme                                           
style-loader                      0.13.1  0.13.1 0.16.1 devDependencies https://github.com/webpack/style-loader#readme                                    
typescript                        2.0.3   2.0.3  2.2.2  devDependencies http://typescriptlang.org/                                                        
```

**Comment by kabir** [comment]
Best thing to do is probably to try `yarn start` and `yarn test` with the micro updates first, and then with the micros, and also try to look out for any new weirdness when running it :)

**Comment by rsvoboda** [comment]
Major components version upgrade will need more attention, unable to run yarn start and yarn test, getting unpleasant errors.

```
yarn start
yarn start v0.21.3
$ webpack-dev-server --inline --progress --port 3000 --config config/webpack.dev.js 
/home/rsvoboda/git/jirban-jira/webapp/node_modules/extract-text-webpack-plugin/index.js:184
		throw new Error("Breaking change: extract now only takes a single argument. Either an options " +
		^

Error: Breaking change: extract now only takes a single argument. Either an options object *or* the loader(s).
Example: if your old code looked like this:
    ExtractTextPlugin.extract('style-loader', 'css-loader')

You would change it to:
    ExtractTextPlugin.extract({ fallback: 'style-loader', use: 'css-loader' })

The available options are:
    use: string | object | loader[]
    fallback: string | object | loader[]
    publicPath: string

    at Function.ExtractTextPlugin.extract (/home/rsvoboda/git/jirban-jira/webapp/node_modules/extract-text-webpack-plugin/index.js:184:9)
    at Object.<anonymous> (/home/rsvoboda/git/jirban-jira/webapp/config/webpack.common.js:50:35)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/rsvoboda/git/jirban-jira/webapp/config/webpack.dev.js:19:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

```
yarn test
yarn test v0.21.3
$ karma start 
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.resolve.extensions[0] should not be empty.
    at webpack (/home/rsvoboda/git/jirban-jira/webapp/node_modules/webpack/lib/webpack.js:19:9)
    at new Plugin (/home/rsvoboda/git/jirban-jira/webapp/node_modules/karma-webpack/lib/karma-webpack.js:67:16)
    at invoke (/home/rsvoboda/git/jirban-jira/webapp/node_modules/di/lib/injector.js:75:15)
    at Array.instantiate (/home/rsvoboda/git/jirban-jira/webapp/node_modules/di/lib/injector.js:59:20)
    at get (/home/rsvoboda/git/jirban-jira/webapp/node_modules/di/lib/injector.js:48:43)
    at /home/rsvoboda/git/jirban-jira/webapp/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
    at Array.invoke (/home/rsvoboda/git/jirban-jira/webapp/node_modules/di/lib/injector.js:70:31)
    at Injector.get (/home/rsvoboda/git/jirban-jira/webapp/node_modules/di/lib/injector.js:48:43)
    at instantiatePreprocessor (/home/rsvoboda/git/jirban-jira/webapp/node_modules/karma/lib/preprocessor.js:55:20)
    at Array.forEach (native)
    at createPreprocessor (/home/rsvoboda/git/jirban-jira/webapp/node_modules/karma/lib/preprocessor.js:74:20)
    at Array.invoke (/home/rsvoboda/git/jirban-jira/webapp/node_modules/di/lib/injector.js:75:15)
    at get (/home/rsvoboda/git/jirban-jira/webapp/node_modules/di/lib/injector.js:48:43)
    at /home/rsvoboda/git/jirban-jira/webapp/node_modules/di/lib/injector.js:71:14
    at Array.map (native)
01 04 2017 13:22:25.458:ERROR [preprocess]: Can not load "webpack"!
  WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.resolve.extensions[0] should not be empty.
```

**Comment by kabir** [comment]
Done in Overbård

**Comment by rsvoboda** [comment]
Thanks
